name: Test application

on:
  pull_request:
    branches: [draft]

jobs:
  check-files:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      canSkip: ${{ steps.Checker.outputs.canSkip }}
    steps:
      - name: Get files
        uses: actions/checkout@v4
      - name: Get tools
        uses: actions/checkout@v4
        with:
          path: tools/
          repository: openliberty/guides-common
      - id: Checker
        shell: bash
        run: bash ./tools/pr-checker/checker.sh ${{ github.repository }} ${{ github.event.pull_request.number }} | tee checker.log 
      - id: Lint-Code-Base
        if: "! github.event.pull_request.head.repo.fork"
        uses: github/super-linter@latest
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ./tools/pr-checker/linters/
          FILTER_REGEX_EXCLUDE: .*/*.gradle
          DEFAULT_BRANCH: draft
      - name: Summary
        if: "! github.event.pull_request.head.repo.fork"
        run: |
            < ./checker.log tail -n +2; echo "====== Super Linter ======"
            < ./super-linter.log sed -n '/.*The script has completed.*/,$p' | tail -n +4 | sed  's/.*\(\[[A-Z]\+\]\)/\1/'
            echo "====== Examine logs in Checker and Super-Linter steps for more details ======"
            if [ '${{ steps.Checker.outcome }}' != 'success' ] || [ '${{ steps.Lint-Code-Base.outcome }}' != 'success' ]; then exit 1; fi
  test-app:
    runs-on: ubuntu-latest
    needs: [check-files]
    if: "!contains(needs.check-files.outputs.canSkip, 'true')"
    defaults:
      run:
        working-directory: finish

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'semeru'
          java-version: 11
      - run: unset _JAVA_OPTIONS

      - name: Run tests
        run: sudo ../scripts/testApp.sh

      - name: Post tests
        if: always()
        run: |
          sudo chmod -R +rx jar/build
          sudo chmod -R +rx war/build
          sudo chmod -R +rx ear/build
          logsPath=$(sudo find . -name "console.log" | grep ear);
          sudo cat "$logsPath" | sudo grep Launching
      - name: Archive server logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ear-logs
          path: finish/ear/build/wlp/usr/servers/defaultServer/logs/
      - name: Archive reports if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: finish/**/build/reports/